
import React from 'react';

const features = [
  {
    title: "AI-Powered Content",
    description: "Every quiz and roadmap is dynamically generated by advanced AI, ensuring fresh and relevant content every time.",
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
      </svg>
    ),
    module: "01"
  },
  {
    title: "Personalized Learning",
    description: "Get customized learning paths and track your progress across multiple programming languages simultaneously.",
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
      </svg>
    ),
    module: "02"
  },
  {
    title: "Instant Feedback",
    description: "Receive detailed explanations for every question and comprehensive progress tracking to master concepts faster.",
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    ),
    module: "03"
  }
];

const Features: React.FC = () => {
  return (
    <section id="about" className="py-24 px-6 border-t border-white/5">
      <div className="max-w-7xl mx-auto">
        <div className="mb-16">
          <h2 className="text-4xl md:text-5xl font-bold tracking-tighter mb-4">Why Choose LearnAI?</h2>
          <p className="text-zinc-500 max-w-xl text-lg font-light">
            We've built a complete ecosystem designed to accelerate your mastery of programming 
            through the power of generative intelligence.
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-0 border border-white/10">
          {features.map((feature, idx) => (
            <div 
              key={idx} 
              className={`group p-10 transition-all duration-500 hover:bg-zinc-900/50 border-white/10 ${
                idx !== features.length - 1 ? 'md:border-r border-b md:border-b-0' : 'border-b md:border-b-0'
              }`}
            >
              <div className="mb-12 flex justify-between items-start">
                <div className="p-3 bg-white/5 text-purple-500 border border-white/10 group-hover:border-purple-500/50 transition-colors">
                  {feature.icon}
                </div>
                <span className="text-[10px] font-bold text-zinc-600 uppercase tracking-widest">Module {feature.module}</span>
              </div>
              
              <h3 className="text-xl font-bold uppercase tracking-widest mb-4 group-hover:text-purple-400 transition-colors">
                {feature.title}
              </h3>
              
              <p className="text-zinc-400 font-light leading-relaxed">
                {feature.description}
              </p>

              <div className="mt-10 h-1 w-0 bg-purple-600 transition-all duration-700 group-hover:w-full"></div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
